# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'led3cClientGui01.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 163)
        self.gridLayoutWidget = QtWidgets.QWidget(Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 471, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.ledGreen = QtWidgets.QFrame(self.gridLayoutWidget)
        self.ledGreen.setMinimumSize(QtCore.QSize(40, 40))
        self.ledGreen.setMaximumSize(QtCore.QSize(40, 40))
        self.ledGreen.setStyleSheet("background-color: green;\n"
"border-radius: 20px;      \n"
"border: 2px solid #555;")
        self.ledGreen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ledGreen.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ledGreen.setObjectName("ledGreen")
        self.gridLayout.addWidget(self.ledGreen, 0, 1, 1, 1)
        self.ledRed = QtWidgets.QFrame(self.gridLayoutWidget)
        self.ledRed.setMinimumSize(QtCore.QSize(40, 40))
        self.ledRed.setMaximumSize(QtCore.QSize(40, 40))
        self.ledRed.setStyleSheet("background-color: red;\n"
"border-radius: 20px;      \n"
"border: 2px solid #555;")
        self.ledRed.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ledRed.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ledRed.setObjectName("ledRed")
        self.gridLayout.addWidget(self.ledRed, 0, 0, 1, 1)
        self.ledBlue = QtWidgets.QFrame(self.gridLayoutWidget)
        self.ledBlue.setMinimumSize(QtCore.QSize(40, 40))
        self.ledBlue.setMaximumSize(QtCore.QSize(40, 40))
        self.ledBlue.setStyleSheet("background-color: blue;\n"
"border-radius: 20px;      \n"
"border: 2px solid #555;")
        self.ledBlue.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ledBlue.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ledBlue.setObjectName("ledBlue")
        self.gridLayout.addWidget(self.ledBlue, 0, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
