# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'columnDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(312, 273)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.columnView = QtWidgets.QColumnView(Dialog)
        self.columnView.setGeometry(QtCore.QRect(10, 10, 291, 251))
        self.columnView.setObjectName("columnView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)

    # ----- QColumnView 테스트 코드 시작 -----
    # 1) 파일시스템 모델 생성 (Finder/열 방식 탐색에 적합)
    fs = QtWidgets.QFileSystemModel()
    fs.setRootPath(QtCore.QDir.homePath())  # 모델 준비 (이 경로부터 스캔)
    # 숨김/현재/부모 항목 제외 + 폴더/파일 모두 표시
    fs.setFilter(QtCore.QDir.AllDirs | QtCore.QDir.Files | QtCore.QDir.NoDotAndDotDot)

    # 2) ColumnView에 모델 연결 + 루트 인덱스 지정
    ui.columnView.setModel(fs)
    root_index = fs.index(QtCore.QDir.homePath())
    ui.columnView.setRootIndex(root_index)

    # (선택) 아이콘 크기/행 높이 살짝 키우기
    ui.columnView.setIconSize(QtCore.QSize(20, 20))

    # 3) 선택 변경 시 현재 경로를 창 제목에 표시
    def on_current_changed(curr, prev):
        if not curr.isValid():
            return
        Dialog.setWindowTitle(fs.filePath(curr))

    ui.columnView.selectionModel().currentChanged.connect(on_current_changed)
    # ----- QColumnView 테스트 코드 끝 -----

    Dialog.show()
    sys.exit(app.exec_())
