# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(377, 293)
        self.listWidget = QtWidgets.QListWidget(Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 351, 271))
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)

    # ----- QListWidget 테스트 코드 시작 -----
    lw = ui.listWidget

    # 1) 샘플 아이템 추가
    lw.addItems(["Apple", "Banana", "Cherry", "Durian"])
    # (숨은 ID 예시: UserRole에 인덱스 저장)
    for i in range(lw.count()):
        lw.item(i).setData(QtCore.Qt.UserRole, i)

    # 2) 편집/정렬/드래그 설정
    lw.setEditTriggers(
        QtWidgets.QAbstractItemView.DoubleClicked |
        QtWidgets.QAbstractItemView.EditKeyPressed
    )
    lw.setSortingEnabled(True)  # 알파벳 정렬(메뉴로 끄고 켤 수 있음)
    lw.setDragDropMode(QtWidgets.QAbstractItemView.InternalMove)  # 드래그 재정렬

    # 3) 클릭 시 창 제목에 선택 표시
    def on_item_clicked(item: QtWidgets.QListWidgetItem):
        Dialog.setWindowTitle(f"Selected: {item.text()} (id={item.data(QtCore.Qt.UserRole)})")
    lw.itemClicked.connect(on_item_clicked)

    # 4) 오른쪽 클릭 컨텍스트 메뉴(추가/이름바꾸기/삭제)
    lw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)

    def show_menu(pos):
        item = lw.itemAt(pos)
        menu = QtWidgets.QMenu(lw)
        act_add    = menu.addAction("Add Item")
        act_rename = menu.addAction("Rename")
        act_del    = menu.addAction("Delete")
        menu.addSeparator()
        act_sort   = menu.addAction("Toggle Sorting (A↔︎Z)")
        chosen = menu.exec_(lw.mapToGlobal(pos))
        if chosen == act_add:
            text, ok = QtWidgets.QInputDialog.getText(Dialog, "Add Item", "Text:")
            if ok and text:
                lw.addItem(text)
        elif chosen == act_rename and item:
            lw.editItem(item)
        elif chosen == act_del and item:
            lw.takeItem(lw.row(item))
        elif chosen == act_sort:
            lw.setSortingEnabled(not lw.isSortingEnabled())

    lw.customContextMenuRequested.connect(show_menu)
    # ----- QListWidget 테스트 코드 끝 -----

    Dialog.show()
    sys.exit(app.exec_())
