# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(312, 273)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.listView = QtWidgets.QListView(Dialog)
        self.listView.setGeometry(QtCore.QRect(20, 40, 256, 192))
        self.listView.setObjectName("listView")
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)

    model = QtCore.QStringListModel(["Apple", "Banana", "Cherry", "Durian"])
    ui.listView.setModel(model)
    ui.listView.setEditTriggers(
        QtWidgets.QAbstractItemView.DoubleClicked |
        QtWidgets.QAbstractItemView.EditKeyPressed
    )
    def on_clicked(index):
        text = model.data(index, QtCore.Qt.DisplayRole)
        Dialog.setWindowTitle(f"Selected: {text}")
    ui.listView.clicked.connect(on_clicked)
        
    Dialog.show()    
    sys.exit(app.exec_())
