# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tableDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(312, 273)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(10, 10, 291, 251))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)

# ------------------- QTableView 테스트 코드 시작 -------------------
    def make_item(value, editable=True, align_right=False):
        it = QtGui.QStandardItem(str(value))
        it.setEditable(editable)
        if align_right:
            it.setTextAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        return it

    # 1) 모델 생성 및 헤더
    model = QtGui.QStandardItemModel()
    model.setHorizontalHeaderLabels(["ID", "Temp(°C)", "Humi(%)", "Status"])

    # 2) 샘플 행 추가
    rows = [
        ["A-001", 22.4, 41.0, "OK"],
        ["A-002", 23.1, 43.2, "ALERT"],
        ["A-003", 22.6, 40.7, "OK"],
    ]
    for r in rows:
        model.appendRow([
            make_item(r[0], editable=False),              # ID: 읽기전용
            make_item(r[1], editable=True,  align_right=True),  # Temp
            make_item(r[2], editable=True,  align_right=True),  # Humi
            make_item(r[3], editable=True)                # Status
        ])

    # 3) 뷰에 모델 연결 + 보기 옵션
    tv = ui.tableView
    tv.setModel(model)
    tv.setSelectionBehavior(QtWidgets.QTableView.SelectRows)   # 행 단위 선택
    tv.setSelectionMode(QtWidgets.QTableView.SingleSelection)
    tv.setSortingEnabled(True)                                 # 헤더 클릭 정렬
    tv.resizeColumnsToContents()
    tv.horizontalHeader().setStretchLastSection(True)          # 마지막 열 늘리기
    tv.setAlternatingRowColors(True)

    # 4) 선택 변경 시 창 제목에 행 요약 표시
    def on_current_changed(curr: QtCore.QModelIndex, prev: QtCore.QModelIndex):
        if not curr.isValid():
            return
        r = curr.row()
        id_  = model.index(r, 0).data()
        t    = model.index(r, 1).data()
        h    = model.index(r, 2).data()
        stat = model.index(r, 3).data()
        Dialog.setWindowTitle(f"Selected: {id_} | T={t}°C, H={h}%, {stat}")

    tv.selectionModel().currentChanged.connect(on_current_changed)
    # ------------------- QTableView 테스트 코드 끝 -------------------

    Dialog.show()
    sys.exit(app.exec_())
