# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treeDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(312, 273)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.treeView = QtWidgets.QTreeView(Dialog)
        self.treeView.setGeometry(QtCore.QRect(10, 10, 291, 251))
        self.treeView.setObjectName("treeView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)

 # ----- 트리 뷰 테스트 코드 -----
    model = QtGui.QStandardItemModel()
    model.setHorizontalHeaderLabels(["Name", "Value"])
    root = model.invisibleRootItem()

    sensors = QtGui.QStandardItem("Sensors"); sensors.setEditable(False)
    root.appendRow([sensors, QtGui.QStandardItem("")])

    temp = QtGui.QStandardItem("Temperature")
    temp.setCheckable(True)
    temp.setCheckState(QtCore.Qt.Checked)   # ← setChecked가 아니라 setCheckState 사용
    sensors.appendRow([temp, QtGui.QStandardItem("22.4 ℃")])

    humi = QtGui.QStandardItem("Humidity")
    sensors.appendRow([humi, QtGui.QStandardItem("41.0 %")])

    machines = QtGui.QStandardItem("Machines"); machines.setEditable(False)
    root.appendRow([machines, QtGui.QStandardItem("")])
    machines.appendRow([QtGui.QStandardItem("Conveyor A"), QtGui.QStandardItem("OK")])
    machines.appendRow([QtGui.QStandardItem("Mixer B"),    QtGui.QStandardItem("Idle")])

    ui.treeView.setModel(model)
    ui.treeView.expandAll()
    ui.treeView.setAlternatingRowColors(True)
    ui.treeView.header().setStretchLastSection(True)
    ui.treeView.resizeColumnToContents(0)

    def on_current_changed(curr: QtCore.QModelIndex, prev: QtCore.QModelIndex):
        if not curr.isValid():
            return
        name_index  = curr.sibling(curr.row(), 0)
        value_index = curr.sibling(curr.row(), 1)
        name  = model.data(name_index,  QtCore.Qt.DisplayRole)
        value = model.data(value_index, QtCore.Qt.DisplayRole) or ""
        Dialog.setWindowTitle(f"{name}: {value}")

    ui.treeView.selectionModel().currentChanged.connect(on_current_changed)
    # ----- /트리 뷰 테스트 코드 -----

    Dialog.show()
    sys.exit(app.exec_())
