# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'treeWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(377, 293)
        self.treeWidget = QtWidgets.QTreeWidget(Dialog)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 361, 271))
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setText(0, "1")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)

    # ----- QTreeWidget 테스트 코드 시작 -----
    tw = ui.treeWidget

    # 1) 헤더/컬럼 구성
    tw.setColumnCount(2)
    tw.setHeaderLabels(["Name", "Value"])

    # 2) 트리 데이터 추가
    from PyQt5.QtWidgets import QTreeWidgetItem

    sensors = QTreeWidgetItem(["Sensors", ""])
    tw.addTopLevelItem(sensors)

    temp = QTreeWidgetItem(["Temperature", "22.4 ℃"])
    temp.setCheckState(0, QtCore.Qt.Checked)   # 체크박스 예시
    sensors.addChild(temp)

    humi = QTreeWidgetItem(["Humidity", "41.0 %"])
    sensors.addChild(humi)

    machines = QTreeWidgetItem(["Machines", ""])
    tw.addTopLevelItem(machines)
    machines.addChild(QTreeWidgetItem(["Conveyor A", "OK"]))
    machines.addChild(QTreeWidgetItem(["Mixer B", "Idle"]))

    # 3) 보기 옵션
    tw.expandAll()
    tw.setAlternatingRowColors(True)
    tw.header().setStretchLastSection(True)
    tw.resizeColumnToContents(0)
    tw.setEditTriggers(
        QtWidgets.QAbstractItemView.DoubleClicked |
        QtWidgets.QAbstractItemView.EditKeyPressed
    )
    tw.setSortingEnabled(True)  # 헤더 클릭 정렬

    # 4) 선택 시 창 제목에 표시
    def on_item_clicked(item, col):
        Dialog.setWindowTitle(f"선택: {item.text(0)} | 값: {item.text(1)}")
    tw.itemClicked.connect(on_item_clicked)

    # 5) 우클릭 컨텍스트 메뉴(자식 추가/이름바꾸기/삭제)
    tw.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)

    def show_menu(pos):
        item = tw.itemAt(pos)
        menu = QtWidgets.QMenu(tw)
        act_add_child = menu.addAction("Add Child")
        act_rename    = menu.addAction("Rename")
        act_delete    = menu.addAction("Delete")
        chosen = menu.exec_(tw.viewport().mapToGlobal(pos))

        if chosen == act_add_child:
            child = QTreeWidgetItem(["New Item", ""])
            if item:
                item.addChild(child)
                tw.setCurrentItem(child)
            else:
                tw.addTopLevelItem(child)
            tw.editItem(child, 0)

        elif chosen == act_rename and item:
            tw.editItem(item, 0)

        elif chosen == act_delete and item:
            parent = item.parent()
            if parent:
                parent.removeChild(item)
            else:
                idx = tw.indexOfTopLevelItem(item)
                tw.takeTopLevelItem(idx)

    tw.customContextMenuRequested.connect(show_menu)
    # ----- QTreeWidget 테스트 코드 끝 -----



    Dialog.show()
    sys.exit(app.exec_())
