# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'undoDemo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(312, 273)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.undoView = QtWidgets.QUndoView(Dialog)
        self.undoView.setGeometry(QtCore.QRect(10, 10, 291, 261))
        self.undoView.setObjectName("undoView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()    
    ui.setupUi(Dialog)

    # ----- Undo/Redo 테스트 코드 시작 -----

    # 0) 라벨/버튼 배치(undoView가 폼을 꽉 채우므로 살짝 아래로 내립니다)
    ui.undoView.setGeometry(QtCore.QRect(10, 70, 291, 201))

    label = QtWidgets.QLabel("Hello", Dialog)
    label.setGeometry(QtCore.QRect(10, 10, 180, 24))

    btnDo   = QtWidgets.QPushButton("Append '!'", Dialog)
    btnUndo = QtWidgets.QPushButton("Undo",        Dialog)
    btnRedo = QtWidgets.QPushButton("Redo",        Dialog)
    btnDo.setGeometry(10, 35, 90, 24)
    btnUndo.setGeometry(110, 35, 80, 24)
    btnRedo.setGeometry(200, 35, 80, 24)

    # 1) Undo 스택 생성 + View 연결
    stack = QtWidgets.QUndoStack(Dialog)
    ui.undoView.setStack(stack)

    # 2) 커맨드 정의: 라벨에 "!" 추가
    class AppendBangCmd(QtWidgets.QUndoCommand):
        def __init__(self, label):
            super().__init__("Append '!'")
            self.label = label
            self.prev  = label.text()

        def redo(self):
            self.label.setText(self.prev + "!")
        def undo(self):
            self.label.setText(self.prev)

    # 3) 버튼/단축키 연결
    btnDo.clicked.connect(lambda: stack.push(AppendBangCmd(label)))
    btnUndo.clicked.connect(stack.undo)
    btnRedo.clicked.connect(stack.redo)

    # Ctrl+Z / Ctrl+Y 단축키
    QtWidgets.QShortcut(QtGui.QKeySequence.Undo, Dialog, stack.undo)
    QtWidgets.QShortcut(QtGui.QKeySequence.Redo, Dialog, stack.redo)

    # 4) 현재 선택된 커맨드에 맞춰 창 제목 갱신(동작 확인용)
    def on_index_changed(_):
        Dialog.setWindowTitle(f"Undo: {stack.undoText() or '-'} | Redo: {stack.redoText() or '-'}")
    stack.indexChanged.connect(on_index_changed)
    on_index_changed(0)  # 초기 타이틀 설정

    # ----- Undo/Redo 테스트 코드 끝 -----

    Dialog.show()
    sys.exit(app.exec_())
